name: Deploy to Pages

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Git
      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Commit and push to the `pages` branch
      - name: Push to Pages branch
        run: |
          # Switch to the pages branch (create it if it doesn't exist)
          git checkout -b pages || git checkout pages

          # Merge changes from the main branch
          git merge main --no-ff --no-commit

          # Commit the changes
          git commit -am "Sync from main excluding certain files"

          # Push to the `pages` branch
          git push origin pages --force
