name: Sync main to pages

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Checkout or create the pages branch
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/remotes/origin/pages; then
            git checkout pages
          else
            git checkout --orphan pages
          fi

      - name: Merge changes from main
        run: |
          git merge origin/main --no-ff -m "Sync changes from main to pages branch"

      - name: Push changes to pages branch
        run: |
          git push origin pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
