name: Sync main to pages

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git
        uses: actions/setup-git@v3

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Checkout the pages branch
        run: git checkout pages || git checkout --orphan pages

      - name: Merge main into pages
        run: |
          git merge main --no-ff -m "Sync changes from main to pages branch"

      - name: Push changes to pages branch
        run: git push origin pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
