name: Sync Folders to Pages Branch

on:
  push:
    branches:
      - main

jobs:
  sync-folders:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Git user
      - name: Configure Git User
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Checkout the pages branch
      - name: Checkout Pages Branch
        run: |
          git fetch origin pages
          git checkout pages

      # Define the list of folders to copy (directly in the workflow)
      - name: Define Folders to Copy
        id: define-folders
        run: |
          FOLDERS_TO_COPY=(
            "CV/*"
            "Czech/*"
            "Math/*"
            "MyPackages/*"
          )
          echo "FOLDERS_TO_COPY=${FOLDERS_TO_COPY[@]}" >> $GITHUB_ENV

      # Copy the folders from the main branch
      - name: Copy Folders from Main Branch
        run: |
          for folder in "${FOLDERS_TO_COPY[@]}"; do
            echo "Copying $folder from main to pages branch..."
            git checkout main -- "$folder"
          done

      # Commit and Push Changes to Pages Branch
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Sync selected folders from main to pages branch" || echo "No changes to commit"
          git push origin pages
