name: Sync to Pages Branch

on:
  push:
    branches:
      - main

jobs:
  sync-folders:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Git user
      - name: Configure Git User
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Checkout the pages branch
      - name: Checkout Pages Branch
        run: |
          git fetch origin pages
          git checkout pages

      # Copy folders listed in files-to-copy.txt
      - name: Read and Copy Files
        run: |
          # Read the list of files from files-to-copy.txt
          while IFS= read -r file; do
            if [ -n "$file" ]; then
              echo "Copying $file..."
              git checkout main -- "$file"
            fi
          done < files-to-copy.txt

      # Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Sync files from main branch to pages branch" || echo "No changes to commit"
          git push origin pages
