name: Update pages branch from main

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allow GITHUB_TOKEN to push changes

jobs:
  update-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main-branch

      - name: Checkout the pages branch
        uses: actions/checkout@v3
        with:
          ref: pages
          path: pages-branch

      - name: Copy files from main to pages
        run: |
          cp -r main-branch/* pages-branch/
          cp -r main-branch/.* pages-branch/ || true  # Include hidden files (e.g., .gitignore), ignore errors

      - name: Commit and push changes to pages
        run: |
          cd pages-branch
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Stage and commit the changes
          git add .
          git commit -m "Update pages branch with files from main" || echo "No changes to commit"

          # Push changes
          git push origin pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
